name: 'ARM'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  arm:
    name: 'arm template checks'
    runs-on: ubuntu-latest
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: ARM Template Toolkit (ARM TTK)
      id: testARM
      uses: aliencube/arm-ttk-actions@v0.3
      with:
        # ARM Template file path to run the test. It can be either a directory or single file.
        path: ./main.json

    - name: Test result - files
      shell: bash
      continue-on-error: true
      run: |
        echo "${{ toJSON(fromJSON(steps.testARM.outputs.results)) }}"
        
    - name: Checkov GitHub Action
      # You may pin to the exact commit or the version.
      uses: bridgecrewio/checkov-action@v12.1347.0
      #with:
           # comma separated list of external (custom) checks repositories
        #external_checks_repos: # optional


    #######
    # Login to Azure and publish bicep to private registry (ACR).
    #######

    #- name: Azure Login
    #  uses: azure/login@v1
    #  with:
    #    creds: ${{ secrets.AZURE_CREDENTIALS }}

    #- name: Azure CLI script
    #  uses: azure/CLI@v1
    #  with:
    #    azcliversion: 2.30.0
    #    inlineScript: |
    #      az bicep publish --file main.bicep --target "br:{registry}/{module_path}:{tag}" --documentationUri ${{  }}